import yaml

from snakemake.utils import min_version, validate

min_version("8.10")


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your includes here.
include: "rules/_utils.smk"
include: "rules/automatic.smk"
include: "rules/prepare.smk"
include: "rules/impute.smk"
include: "rules/aggregate.smk"
include: "rules/solar.smk"


# Run additional validation on the configuration file.
additional_config_validation()

# Add all files to be delivered alongside the workflow here
workflow.source_path("scripts/_gem.py")
workflow.source_path("scripts/_plots.py")
workflow.source_path("scripts/_schemas.py")
workflow.source_path("scripts/_utils.py")


rule all:
    message:
        "ERROR: Invalid `rule all:` call"
    default_target: True
    output:
        "INVALID",
    log:
        stderr="logs/all.stderr",
    conda:
        "envs/shell.yaml"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
