import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    # User resources
    imputed_powerplants="<resources>/user/{shapes}/impute/{category}.parquet",
    proxy_rooftop_pv="<resources>/user/{shapes}/proxies/rooftop_pv.tif",
    shapes="<resources>/user/{shapes}/shapes.parquet",
    wemi="<resources>/user/WEMI.xls",
    # Module results
    aggregated_capacity="<results>/{shapes}/aggregated/{adjustment}/{category}.parquet",
    powerplants="<results>/{shapes}/powerplants/{adjustment}/{category}.parquet",


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))

# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)


# Add all your includes here.
include: "rules/_utils.smk"
include: "rules/automatic.smk"
include: "rules/prepare.smk"
include: "rules/impute.smk"
include: "rules/aggregate.smk"
include: "rules/solar.smk"


# Run additional validation on the configuration file.
additional_config_validation()

# Add all files to be delivered alongside the workflow here
workflow.source_path("scripts/_gem.py")
workflow.source_path("scripts/_plots.py")
workflow.source_path("scripts/_schemas.py")
workflow.source_path("scripts/_utils.py")


rule all:
    default_target: True
    output:
        "INVALID",
    log:
        stderr="<logs>/all.stderr",
    conda:
        "envs/shell.yaml"
    message:
        "ERROR: Invalid `rule all:` call"
    shell:
        'echo "This workflow must be called as a snakemake module." > {log.stderr}'
