[workspace]
name = "module_powerplants"
authors = ["See AUTHORS file"]
description = "Aggregate global powerplant capacities into any resolution."
license = "Apache-2.0"
readme = "README.md"
channels = ["conda-forge", "bioconda"]
platforms = ["win-64", "linux-64", "osx-arm64"]
homepage = "https://www.modelblocks.org/"

[dependencies]
clio-tools = ">=2026.03.30"
conda = ">=25.0.0"
ipdb = ">=0.13.13"
ipykernel = ">=6.29.5"
jsonschema = ">=4.0.0"
mypy = ">=1.15.0"
pytest = ">=8.3.5"
python = ">=3.12"
ruff = ">=0.9.9"
snakefmt = ">=0.10.2"
snakemake-minimal = ">=8.29.0"
pytz = ">=2026.1.post1"
pyarrow = ">=23.0.1,<24"

[tasks]
test-integration = {cmd = "pytest tests/integration_test.py"}

[feature.powerplants]
channels = ["conda-forge", "nodefaults"]

[feature.powerplants.dependencies]
click = "8.2.1.*"
cmap = "0.7.1.*"
dask = "2025.7.0.*"
geopandas = "1.0.1.*"
ipdb = "0.13.13.*"
openpyxl = "3.1.5.*"
numpy = "2.3.5.*"
matplotlib = "3.10.3.*"
pandas = "2.3.0.*"
pandera-geopandas = "0.24.0.*"
pyarrow = "19.0.1.*"
pyproj = "3.7.1.*"
python = "3.12.9.*"
pyyaml = "6.0.2.*"
xlrd = "2.0.1.*"
pip = "25.1.1.*"
mypy = "1.20.1.*"

[feature.powerplants.pypi-dependencies]
gregor = { git = "https://github.com/jnnr/gregor.git", rev = "fix-memory-explosion" }

[environments]
powerplants = { features = ["powerplants"], no-default-feature = true }
