# Emulate a user configuring the module.
configfile: workflow.source_path("test_config.yaml")

# Import the module and configure it.
# `snakefile:` specifies the module. It can use file paths and special github(...) / gitlab(...) markers
# `prefix:` re-routes all input/output paths of the module, helping to avoid file conflicts.
module module_powerplants:
    snakefile: "../../workflow/Snakefile"
    config: config
    prefix: "results/module_powerplants/"

# rename all module rules with a prefix, to avoid naming conflicts.
use rule * from module_powerplants as module_powerplants_*

# Request something from the module
rule all:
    message: "A generic test case for your module."
    default_target: True
    input:
        "results/module_powerplants/resources/automatic/prepared/hydropower.parquet"
