# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    eia_bulk: "https://www.eia.gov/opendata/bulk/INTL.zip"
    gem:
      integrated: https://globalenergymonitor.org/wp-content/uploads/2025/04/Global-Integrated-Power-April-2025.xlsx
      solar: https://globalenergymonitor.org/wp-content/uploads/2025/02/Global-Solar-Power-Tracker-February-2025.xlsx
    glohydrores: "https://zenodo.org/records/14526360/files/GloHydroRes_vs1.csv"
    tz-sam: "https://blog.transitionzero.org/hubfs/Data%20Products/TZ-SAM/TZ-SAM_Solar%20Asset%20Mapper%20-%20Q1%202025.zip"
gem:
  fuel_mapping:
    "fossil gas: natural gas": "natural gas"
    "fossil gas: LNG": "natural gas"
    "fossil gas: waste heat from natural gas": "waste heat"
    "industrial by-product": "waste heat"
    "fossil gas: coalbed methane": "natural gas"
    "fossil liquids: crude oil": "oil"
    "fossil liquids: diesel": "diesel"
    "fossil liquids: fuel oil": "oil"
    "fossil liquids: heavy fuel oil": "oil"
    "fossil liquids: light fuel oil": "oil"
    "fossil liquids: petroleum coke": "oil"
    "fossil liquids: jet fuel": "oil"
    "fossil liquids: liquefied petroleum gas": "oil"
    "fossil liquids: naphtha": "oil"
    "fossil liquids: gasoline": "gasoline"
    "other: hydrogen (green)": "hydrogen"
    "other: hydrogen (unknown)": "hydrogen"
    "fossil liquids: waste/other oil": "oil"
    "fossil liquids: kerosene": "oil"
    "fossil gas: gaseous propane": "oil"
    "bituminous": "hard coal"
    "lignite": "brown coal"
    "subbituminous": "brown coal"
    "waste coal": "brown coal"
    "anthracite": "hard coal"
    "bioenergy: unknown": "biomass"
    "bioenergy: refuse (municipal and industrial wastes)": "solid waste"
    "bioenergy: paper mill wastes": "biomass"
    "bioenergy: refuse (landfill gas)": "biogas"
    "bioenergy: agricultural waste (biogas)": "biogas"
    "bioenergy: wood & other biomass (solids)": "biomass"
    "bioenergy: agricultural waste (solids)": "biomass"
    "bioenergy: agricultural waste (syngas)": "syngas"
    "bioenergy: agricultural waste (unknown)": "biomass"
    "bioenergy: biodiesel": "diesel"
    "bioenergy: ethanol": "ethanol"
    "bioenergy: refuse (syngas)": "syngas"
    "bioenergy: wastewater and sewage sludge (solids or biogas)": "biomass"
    "bioenergy: wood & other biomass (biocoal)": "biomass"
    "bioenergy: wood & other biomass (syngas)": "syngas"
    "other: tires": "solid waste"
    "hydrogen": "hydrogen"
