# A minimal example of how to configure this module
categories:
  default_fuel:
    bioenergy: biomass
    coal: brown coal
    oil_gas: natural gas
  technology_mapping:
    coal:
      "IGCC": "igcc"
      "subcritical": "steam turbine"
      "supercritical": "steam turbine"
      "ultra-supercritical": "steam turbine"
      "CFB": "steam turbine"
      "unknown": "steam turbine"
    oil_gas:
      "AFC": "ccgt"
      "combined cycle": "ccgt"
      "gas turbine": "ocgt"
      "ICCC": "ccgt"
      "IGCC": "igcc"
      "internal combustion": "reciprocating engine"
      "ISCC": "ccgt"
      "steam turbine": "steam turbine"
      "unknown": "ocgt"
    bioenergy:
      "unknown": "steam turbine"
    nuclear:
      "pressurized heavy water reactor": "steam turbine"
      "pressurized water reactor": "steam turbine"
      "small modular reactor": "steam turbine"
      "heavy water light water reactor": "steam turbine"
      "high temperature gas reactor": "steam turbine"
      "fast breeder reactor": "steam turbine"
      "molten salt reactor": "steam turbine"
      "boiling water reactor": "steam turbine"
      "heavy water gas-cooled reactor": "steam turbine"
      "gas-cooled reactor": "steam turbine"
      "light water graphite reactor": "steam turbine"
      "steam-generating heavy water reactor": "steam turbine"
      "liquid-metal-cooled fast reactor": "steam turbine"
      "fast neutron reactor": "steam turbine"
      "unknown": "steam turbine"
    geothermal:
      "unknown": "high enthalpy geothermal"
      # based on https://doi.org/10.1016/j.ijft.2023.100323
      "binary cycle": "low enthalpy geothermal"
      "flash steam - double": "low enthalpy geothermal"
      "flash steam - triple": "low enthalpy geothermal"
      "dry steam": "high enthalpy geothermal"
      "flash steam - single": "high enthalpy geothermal"
      "flash steam - unknown": "high enthalpy geothermal"
      # based on https://doi.org/10.1146/annurev.energy.22.1.305
      "geopressured geothermal system (GGS)": "high enthalpy geothermal"
      # based on https://www.nature.com/articles/s44359-024-00019-9.pdf
      "advanced geothermal systems (AGS)": "high enthalpy geothermal"
      "enhanced geothermal systems (EGS)": "high enthalpy geothermal"
    hydropower:
      "STO": "reservoir"
      "Canal": "run of river"
      "ROR": "run of river"
      "PS": "pump storage"
      "unknown": "reservoir"
lifetime:
  hydropower: 80
  wind: 25
solar:
  utility_pv:
    dc_ac_ratio: 1.25  # 100 MWdc -> 80 MWac
    lifetime: 25
  concentrated_solar:
    dc_ac_ratio: 1.25  # 100 MWdc -> 80 MWac
    lifetime: 25
wind:
  source: "gem"  # options: wemi, gem_gwpt
  offshore:
    lifetime: 30
  onshore:
    lifetime: 30
coal:
  technology_mapping:
    "IGCC": "igcc"
    "subcritical": "steam turbine"
    "supercritical": "steam turbine"
    "ultra-supercritical": "steam turbine"
    "CFB": "steam turbine"
    "unknown": "steam turbine"
  fuel_mapping:
    "unknown": "brown coal"
    "bituminous": "hard coal"
    "anthracite": "hard coal"
    "lignite": "brown coal"
    "subbituminous": "brown coal"
    "waste coal": "brown coal"
    "bioenergy": "biomass"
    "fossil gas": "natural gas"
    "fossil liquids": "oil"
    "industrial by-product": "solid waste"
    "other": "oil"
