# A minimal example of how to configure this module
categories:
  default_fuel:
    bioenergy: biomass
    coal: brown coal
    oil_gas: natural gas
  technology_mapping:
    coal:
      "IGCC": "igcc"
      "subcritical": "steam turbine"
      "supercritical": "steam turbine"
      "ultra-supercritical": "steam turbine"
      "CFB": "steam turbine"
      "unknown": "steam turbine"
    oil_gas:
      "AFC": "ccgt"
      "combined cycle": "ccgt"
      "gas turbine": "ocgt"
      "ICCC": "ccgt"
      "IGCC": "igcc"
      "internal combustion": "reciprocating engine"
      "ISCC": "ccgt"
      "steam turbine": "steam turbine"
      "unknown": "ocgt"
    bioenergy:
      "unknown": "steam turbine"
    nuclear:
      "pressurized heavy water reactor": "steam turbine"
      "pressurized water reactor": "steam turbine"
      "small modular reactor": "steam turbine"
      "heavy water light water reactor": "steam turbine"
      "high temperature gas reactor": "steam turbine"
      "fast breeder reactor": "steam turbine"
      "molten salt reactor": "steam turbine"
      "boiling water reactor": "steam turbine"
      "heavy water gas-cooled reactor": "steam turbine"
      "gas-cooled reactor": "steam turbine"
      "light water graphite reactor": "steam turbine"
      "steam-generating heavy water reactor": "steam turbine"
      "liquid-metal-cooled fast reactor": "steam turbine"
      "fast neutron reactor": "steam turbine"
      "unknown": "steam turbine"
    geothermal:
      "dry steam": "high enthalpy geothermal"
      "flash steam - single": "high enthalpy geothermal"
      "flash steam - double": "high enthalpy geothermal"
      "flash steam - unknown": "high enthalpy geothermal"
      "flash steam - triple": "high enthalpy geothermal"
      "unknown": "high enthalpy geothermal"
      "binary cycle": "medium enthalpy geothermal"
      "advanced geothermal systems (AGS)": "medium enthalpy geothermal"
      "geopressured geothermal system (GGS)": "medium enthalpy geothermal"
      "enhanced geothermal systems (EGS)": "deep geothermal"
    hydropower:
      "STO": "reservoir"
      "Canal": "run of river"
      "ROR": "run of river"
      "PS": "pump storage"
      "unknown": "reservoir"

fuel_mapping:
  "fossil gas: natural gas": "natural gas"
  "fossil gas: LNG": "natural gas"
  "fossil gas: waste heat from natural gas": "waste heat"
  "industrial by-product": "waste heat"
  "fossil gas: coalbed methane": "natural gas"
  "fossil liquids: crude oil": "oil"
  "fossil liquids: diesel": "diesel"
  "fossil liquids: fuel oil": "oil"
  "fossil liquids: heavy fuel oil": "oil"
  "fossil liquids: light fuel oil": "oil"
  "fossil liquids: petroleum coke": "oil"
  "fossil liquids: jet fuel": "oil"
  "fossil liquids: liquefied petroleum gas": "oil"
  "fossil liquids: naphtha": "oil"
  "fossil liquids: gasoline": "gasoline"
  "other: hydrogen (green)": "hydrogen"
  "other: hydrogen (unknown)": "hydrogen"
  "fossil liquids: waste/other oil": "oil"
  "fossil liquids: kerosene": "oil"
  "fossil gas: gaseous propane": "oil"
  "bituminous": "hard coal"
  "lignite": "brown coal"
  "subbituminous": "brown coal"
  "waste coal": "brown coal"
  "anthracite": "hard coal"
  "bioenergy: unknown": "biomass"
  "bioenergy: refuse (municipal and industrial wastes)": "solid waste"
  "bioenergy: paper mill wastes": "biomass"
  "bioenergy: refuse (landfill gas)": "biogas"
  "bioenergy: agricultural waste (biogas)": "biogas"
  "bioenergy: wood & other biomass (solids)": "biomass"
  "bioenergy: agricultural waste (solids)": "biomass"
  "bioenergy: agricultural waste (syngas)": "syngas"
  "bioenergy: agricultural waste (unknown)": "biomass"
  "bioenergy: biodiesel": "diesel"
  "bioenergy: ethanol": "ethanol"
  "bioenergy: refuse (syngas)": "syngas"
  "bioenergy: wastewater and sewage sludge (solids or biogas)": "biomass"
  "bioenergy: wood & other biomass (biocoal)": "biomass"
  "bioenergy: wood & other biomass (syngas)": "syngas"
  "other: tires": "solid waste"
  "hydrogen": "hydrogen"
